name: Build and Publish Extension

on:
  push:
    branches: [main]
    tags: ['v*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
      
      - name: Build extension
        run: npm run build
      
      - name: Create ZIP file
        run: |
          cd dist
          zip -r ../definite-url-saver.zip .
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension-zip-${{ github.sha }}
          path: definite-url-saver.zip
          retention-days: 30

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: extension-zip-${{ github.sha }}
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: definite-url-saver.zip
          body: |
            ## 🚀 Definite URL Saver - ${{ github.ref_name }}

            ### Como usar:
            1. Instale a extensão no Chrome a partir da URL:
                [Definite URL Saver](https://chromewebstore.google.com/detail/definitive-url-saver/jeegndlfnbahdkklhplahkofoadcgcic)
            
            ### 📦 Como instalar a partir do seu localhost:
            1. Baixe o arquivo `definite-url-saver.zip`
            2. Extraia o conteúdo
            3. Abra `chrome://extensions/` no Chrome
            4. Ative o "Modo do desenvolvedor" (canto superior direito)
            5. Clique em "Carregar sem compactação"
            6. Selecione a pasta extraída
            
            ### 📋 Changelog:
            - Nova versão ${{ github.ref_name }}
            
            ---
            *Build gerado automaticamente pelo GitHub Actions*
          draft: false
          prerelease: false
